<?xml version="1.0" encoding="utf-8" ?>
<MarkMark version="1.0" file="m.crtip.png">
	<Lines>
		<Line x="896" y="20" w="49"/>
		<Line x="406" y="21" w="7"/>
		<Line x="551" y="0" h="45"/>
		<Line x="487" y="8" h="26"/>
		<Line x="438" y="1" h="7"/>
	</Lines>
</MarkMark>
