<?xml version="1.0" encoding="utf-8" ?>
<MarkMark version="1.0" file="01-µçÉÌ-Ö÷Ò³-gai.jpg">
	<Blocks>
		<Block x="1079" y="0" w="61" h="266"/>
	</Blocks>
	<Lines>
		<Line x="652" y="0" h="32"/>
		<Line x="360" y="30" w="1200"/>
		<Line x="1195" y="8" h="13"/>
		<Line x="1105" y="0" h="9"/>
		<Line x="1179" y="15" w="16"/>
		<Line x="1256" y="16" w="17"/>
		<Line x="1071" y="15" w="10"/>
		<Line x="1090" y="25" w="16"/>
		<Line x="1346" y="16" w="11"/>
		<Line x="359" y="55" h="57"/>
		<Line x="359" y="59" w="180"/>
		<Line x="535" y="64" w="4"/>
		<Line x="573" y="31" h="27"/>
		<Line x="1255" y="30" h="83"/>
		<Line x="538" y="131" w="707"/>
		<Line x="754" y="29" h="29"/>
		<Line x="707" y="79" w="456"/>
		<Line x="829" y="57" h="34"/>
		<Line x="1163" y="69" w="82"/>
		<Line x="928" y="107" w="25"/>
		<Line x="899" y="92" h="10"/>
		<Line x="709" y="115" w="11"/>
		<Line x="1180" y="127" w="26"/>
		<Line x="1204" y="111" w="40"/>
		<Line x="538" y="125" w="182"/>
		<Line x="1356" y="56" h="36"/>
		<Line x="1356" y="87" w="140"/>
		<Line x="1381" y="30" h="27"/>
		<Line x="1496" y="58" w="63"/>
		<Line x="1393" y="78" w="7"/>
		<Line x="1460" y="78" w="14"/>
		<Line x="1406" y="68" h="14"/>
		<Line x="1461" y="62" w="17"/>
		<Line x="1477" y="95" w="19"/>
		<Line x="1451" y="52" h="5"/>
		<Line x="511" y="136" h="47"/>
		<Line x="573" y="137" h="511"/>
		<Line x="359" y="658" w="208"/>
		<Line x="317" y="29" h="107"/>
		<Line x="462" y="151" h="17"/>
		<Line x="474" y="222" h="16"/>
		<Line x="378" y="206" h="32"/>
		<Line x="383" y="658" h="165"/>
		<Line x="566" y="794" w="249"/>
		<Line x="813" y="815" w="249"/>
		<Line x="468" y="757" h="20"/>
		<Line x="671" y="647" h="12"/>
		<Line x="457" y="688" h="60"/>
		<Line x="490" y="659" h="31"/>
		<Line x="478" y="746" h="11"/>
		<Line x="814" y="667" h="145"/>
		<Line x="548" y="1591" h="15"/>
		<Line x="442" y="1622" h="10"/>
		<Line x="362" y="1606" h="20"/>
		<Line x="407" y="1623" h="11"/>
		<Line x="430" y="1576" h="30"/>
		<Line x="945" y="1630" w="17"/>
		<Line x="359" y="2035" w="211"/>
		<Line x="909" y="1634" h="362"/>
		<Line x="569" y="1828" w="332"/>
	</Lines>
	<Colors>
		<Color x="1084" y="75"/>
		<Color x="1083" y="79"/>
		<Color x="586" y="112"/>
		<Color x="1079" y="76"/>
		<Color x="1081" y="76"/>
		<Color x="1079" y="70"/>
		<Color x="602" y="103"/>
		<Color x="1084" y="71"/>
		<Color x="601" y="109"/>
	</Colors>
</MarkMark>
